name: Publish Docker image

on:
  push: 
    branches: [main]

jobs:
  push_to_registry:
    environment: staging
        
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Debug - Print Docker Hub username
        run: echo "DOCKERHUB_USERNAME:${{ secrets.DOCKERHUB_USERNAME }}"
      
      - name: Debug - Print Docker Hub token
        run: echo "DOCKERHUB_TOKEN:${{ secrets.DOCKERHUB_TOKEN }}"
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: InVision_API
          file: InVision_API/Dockerfile
          push: true
          tags: janoran/in_vision:latest
